spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/onboarder"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  error:
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: my_onboarder.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"